"use client";
import React, { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

export const translations = {
  en: {
    // Loader
    "loader.loading": "Loading experience...",
    // Navbar
    "nav.features": "Features",
    "nav.benefits": "Benefits",
    "nav.workflow": "How It Works",
    "nav.pricing": "Pricing",
    "nav.signin": "Sign In",
    "nav.trial": "Start Free Trial",
    
    // Hero
    "hero.badge": "Built for Laser & CNC Makers",
    "hero.title1": "Run Your Laser",
    "hero.title2": "Business ",
    "hero.titleAccent": "Smarter.",
    "hero.subtitle": "Track materials, calculate costs, manage clients, and generate quotes — all from one beautiful app designed for laser cutters and CNC makers.",
    "hero.ctaTrial": "⚡ Start Free Trial",
    "hero.ctaFeatures": "See Features →",
    "hero.trialNote": "3 days free · then $9/mo · cancel anytime",
    
    // Benefits
    "benefits.badge": "Real Benefits",
    "benefits.title": "Every Feature Saves You",
    "benefits.titleAccent": "Time and Money",
    "benefits.subtitle": "Here is how 0Machine helps you stop wasting hours on admin work and start making more profit.",
    
    "benefits.calc.feature": "Cost Calculator",
    "benefits.calc.title": "Know your true cost per job — instantly",
    "benefits.calc.desc": "Input materials, laser time, electricity, labor, and machine wear. Get a real-time cost breakdown with recommended selling price. Never underprice a job again.",
    "benefits.calc.outcome": "Stop losing money on jobs you thought were profitable",
    "benefits.calc.stat": "3x",
    "benefits.calc.statLabel": "faster quoting",
    
    "benefits.inv.feature": "Material Inventory",
    "benefits.inv.title": "Track every sheet, every cut, every dollar",
    "benefits.inv.desc": "Manage your plywood, acrylic, MDF, and leather stock with real-time inventory value. Get low-stock alerts before you run out mid-project.",
    "benefits.inv.outcome": "Eliminate surprise material shortages during production",
    "benefits.inv.stat": "0",
    "benefits.inv.statLabel": "stockouts",
    
    "benefits.order.feature": "Order Management",
    "benefits.order.title": "Every order tracked from request to delivery",
    "benefits.order.desc": "See all orders at a glance — Pending, In Progress, Completed. Track client names, due dates, revenue earned, and pending payments in one view.",
    "benefits.order.outcome": "Never miss a deadline or forget a client order",
    "benefits.order.stat": "100%",
    "benefits.order.statLabel": "order visibility",
    
    "benefits.presets.feature": "Laser Presets",
    "benefits.presets.title": "Perfect settings every time, zero guesswork",
    "benefits.presets.desc": "Save speed, power, frequency, passes, and air assist settings per material. Load presets instantly when switching between plywood, acrylic, or leather.",
    "benefits.presets.outcome": "Reduce wasted material from wrong machine settings",
    "benefits.presets.stat": "10s",
    "benefits.presets.statLabel": "to load settings",
    
    "benefits.quote.feature": "Quote Generator",
    "benefits.quote.title": "Send professional quotes in under a minute",
    "benefits.quote.desc": "Create detailed quotes with line items, VAT, and totals. Look professional and close deals faster with client-ready documents.",
    "benefits.quote.outcome": "Win more clients with polished, instant quotes",
    "benefits.quote.stat": "60s",
    "benefits.quote.statLabel": "to send a quote",
    
    "benefits.nest.feature": "Nesting Estimator",
    "benefits.nest.title": "Maximize every sheet, minimize every waste",
    "benefits.nest.desc": "Calculate how many parts fit on a sheet before you cut. Optimize material usage and reduce scrap across every job.",
    "benefits.nest.outcome": "Save up to 30% on material costs with smarter nesting",
    "benefits.nest.stat": "30%",
    "benefits.nest.statLabel": "less waste",

    // Feature Showcase
    "features.badge": "Features",
    "features.title": "Designed for the way you work",
    "features.subtitle": "Explore the core tools that make running a workshop effortless.",
    
    "features.tab.dashboard": "Dashboard",
    "features.tab.calc": "Cost Calculator",
    "features.tab.inventory": "Inventory",
    "features.tab.orders": "Order Tracker",
    "features.tab.presets": "Laser Presets",
    
    "features.db.title": "Your entire workshop, one glance",
    "features.db.subtitle": "See total projects, active jobs, completed work, and revenue at a glance. No more guessing where things stand.",
    "features.db.h1": "Real-time project stats",
    "features.db.h2": "Revenue tracking",
    "features.db.h3": "Recent projects feed",
    "features.db.h4": "Status overview",
    
    "features.calc.title": "Real-time cost & profit calculation",
    "features.calc.subtitle": "Input material cost, sheet dimensions, laser time, electricity, machine wear, and labor. See your cost breakdown and recommended selling price instantly.",
    "features.calc.h1": "Material cost per unit",
    "features.calc.h2": "Machine & energy tracking",
    "features.calc.h3": "Profit margin calculator",
    "features.calc.h4": "Recommended pricing",
    
    "features.inv.title": "Live inventory valuation & alerts",
    "features.inv.subtitle": "Track wood, acrylic, and custom materials by the sheet or scrap size. Get automatic notifications when a material drops below your safety threshold.",
    "features.inv.h1": "Plywood & Acrylic logs",
    "features.inv.h2": "Low-stock notifications",
    "features.inv.h3": "Automatic usage deductions",
    "features.inv.h4": "Cost tracking per material",
    
    "features.orders.title": "Visual production pipeline",
    "features.orders.subtitle": "Track status from quote request to final delivery. Set deadlines, record payments, and upload project images for quick visual recall.",
    "features.orders.h1": "Drag & drop status board",
    "features.orders.h2": "Client relationship tracker",
    "features.orders.h3": "Revenue and balance logs",
    "features.orders.h4": "Due date calendars",
    
    "features.presets.title": "Your workshop settings library",
    "features.presets.subtitle": "Never waste material testing cuts again. Save speed, power, frequency, passes, and air settings for different lasers and tube powers.",
    "features.presets.h1": "Multi-machine support",
    "features.presets.h2": "Material thickness tabs",
    "features.presets.h3": "Vector vs. Engrave modes",
    "features.presets.h4": "Instant settings lookup",
    
    "features.tab.nesting": "Nesting Estimator",
    "features.tab.quotes": "Quotes & Invoices",
    "features.tab.clients": "Client Manager",
    "features.tab.analytics": "Analytics",
    
    "features.nest.title": "Optimize layouts and minimize scrap",
    "features.nest.subtitle": "Calculate how many items fit onto a sheet of plywood or acrylic before cutting. Save up to 30% on material costs by nesting parts efficiently.",
    "features.nest.h1": "Visual sheet nesting",
    "features.nest.h2": "Scrap estimator",
    "features.nest.h3": "Yield optimization",
    "features.nest.h4": "Cost savings calculation",

    "features.quotes.title": "Send client-ready PDF quotes and invoices",
    "features.quotes.subtitle": "Convert project estimates into detailed client documents in seconds. Export PDFs with custom bank details, tax settings, and payment links.",
    "features.quotes.h1": "PDF invoice export",
    "features.quotes.h2": "Auto tax calculations",
    "features.quotes.h3": "Billing status tracking",
    "features.quotes.h4": "Custom branding",

    "features.clients.title": "Manage repeat clients and balances",
    "features.clients.subtitle": "Keep track of contact info, orders, and pending payments for every customer. View lifetime value (LTV) to identify your top buyers.",
    "features.clients.h1": "Client ledger",
    "features.clients.h2": "Lifetime value (LTV)",
    "features.clients.h3": "Balance tracking",
    "features.clients.h4": "Quick billing",

    "features.analytics.title": "Understand your business with smart numbers",
    "features.analytics.subtitle": "Track total revenue, completion rates, top-earning projects, material usage, and average cost per job. Know exactly where your profits come from.",
    "features.analytics.h1": "Revenue tracking",
    "features.analytics.h2": "Completion rates",
    "features.analytics.h3": "Top projects stats",
    "features.analytics.h4": "Time & cost analysis",

    // Interactive Mockup Texts
    "mock.total": "Total",
    "mock.inprogress": "In Progress",
    "mock.completed": "Completed",
    "mock.revenue": "Revenue",
    "mock.recent": "RECENT PROJECTS",
    "mock.coasters": "Custom Coasters",
    "mock.birch": "Birch Plywood 3mm",
    "mock.sheet": "Sheet Cost",
    "mock.usage": "Usage",
    "mock.laser": "Laser Time",
    "mock.labor": "Labor",
    "mock.cost": "Total Cost",
    "mock.price": "Rec. Price",
    "mock.wood": "Wood - Birch 3mm",
    "mock.acrylic": "Acrylic - Red 3mm",
    "mock.sheets": "sheets",
    "mock.stock": "In Stock",
    "mock.pending": "Pending",
    "mock.deliv": "Delivered",
    "mock.bal": "Bal. Due",
    "mock.speed": "Speed",
    "mock.power": "Power",
    
    // Comparison
    "comp.badge": "Comparison",
    "comp.title": "Spreadsheets vs",
    "comp.titleAccent": "0Machine",
    "comp.subtitle": "Why makers are ditching Excel for a dedicated planner.",
    "comp.col.old": "Traditional Ways",
    "comp.col.new": "The 0Machine Way",
    "comp.old.1": "Pricing calculated from gut feeling — losing money on every other job",
    "comp.old.2": "Design files scattered across USB drives, desktop folders, and messaging apps",
    "comp.old.3": "Revenue tracked in messy spreadsheets — no idea which projects are profitable",
    "comp.old.4": "Laser settings written on sticky notes — wrong power, wasted material",
    "comp.old.5": "Orders managed in your head — missed deadlines and forgotten clients",
    "comp.old.6": "Material shortages discovered mid-job — production halted, clients waiting",
    "comp.new.1": "Cost Calculator shows real production cost and recommended selling price instantly",
    "comp.new.2": "Every project organized with photos, costs, time, materials, and client info",
    "comp.new.3": "Smart analytics show revenue, top projects, completion rates, and trends",
    "comp.new.4": "Laser Presets loaded in 10 seconds — perfect settings every time",
    "comp.new.5": "Orders tracked from Pending to Completed with due dates and client names",
    "comp.new.6": "Material Inventory shows stock levels and total value — never run out",
    
    // Workflow
    "flow.badge": "How It Works",
    "flow.title": "From Setup to Delivery in",
    "flow.titleAccent": "4 Steps",
    "flow.step1.title": "Upload & Organize",
    "flow.step1.desc": "Add your project with materials, photos, and client details. Use templates to start recurring jobs in seconds.",
    "flow.step2.title": "Calculate & Quote",
    "flow.step2.desc": "Use the Cost Calculator to get your true cost — material, machine time, labor, electricity. Generate a professional quote instantly.",
    "flow.step3.title": "Produce & Track",
    "flow.step3.desc": "Load your Laser Presets, start the built-in timer, and track progress. Move orders from Pending to In Progress automatically.",
    "flow.step4.title": "Deliver & Grow",
    "flow.step4.desc": "Export PDF reports for clients, review your analytics, and see which projects drive the most revenue. Grow with data, not guesswork.",

    // Product Showcase
    "showcase.badge": "Product Showcase",
    "showcase.title": "Built for your browser and mobile",
    "showcase.subtitle": "Access your dashboard from your workshop tablet or phone.",
    "showcase.label.db": "Project Dashboard",
    "showcase.desc.db": "Track every project with cost and time",
    "showcase.label.detail": "Project Details",
    "showcase.desc.detail": "Full cost breakdown with PDF export",
    "showcase.label.stats": "Smart Analytics",
    "showcase.desc.stats": "Revenue, completion rates, and trends",
    
    // Social Proof
    "social.badge": "Testimonials",
    "social.title": "Loved by CNC & Laser Makers",
    "social.subtitle": "Here is what workshop owners are saying about 0Machine Planner.",
    "social.role.laser": "Laser Workshop Owner",
    "social.role.cnc": "CNC Craftsman",
    "social.role.engrave": "Custom Engraver",
    "social.stat.projects": "Projects Tracked",
    "social.stat.satisfaction": "Customer Satisfaction",
    "social.stat.hours": "Hours Saved Monthly",
    "social.stat.rating": "App Store Rating",
    "social.t1.name": "Jason R.",
    "social.t1.role": "Laser Engraving Shop Owner",
    "social.t1.text": "I used to track everything in a messy Notes app. Now I have full cost breakdowns for every project and I know exactly what to charge. The PDF export alone is worth it.",
    "social.t2.name": "Maria C.",
    "social.t2.role": "Custom Sign Maker",
    "social.t2.text": "The client manager feature is brilliant. I have 12 repeat customers and I can now see at a glance how much revenue each one brings in. Game changer for my side business.",
    "social.t3.name": "Tyler P.",
    "social.t3.role": "CNC Workshop Owner",
    "social.t3.text": "Machine profiles changed everything. I have 3 machines with completely different settings — now I load the profile and I'm ready to go. Never mess up settings again.",
    "social.t4.name": "Emma K.",
    "social.t4.role": "Craft Fair Vendor",
    "social.t4.text": "Super clean UI and super fast. I love that the app works offline too. I use it at craft fairs to show clients exactly what the project will cost before I commit.",
    "social.t5.name": "David M.",
    "social.t5.role": "Etsy Laser Creator",
    "social.t5.text": "The templates feature is a massive time saver. I have templates set up for my most popular laser cut items and I can start a new job in 10 seconds flat. Love it.",
    "social.t6.name": "Rachel S.",
    "social.t6.role": "Small Batch Producer",
    "social.t6.text": "3 day free trial sealed the deal. I had it set up with 5 projects within the first hour. By day 2 I already knew I wasn't cancelling. Worth every dollar.",
    
    // Pricing
    "price.badge": "Simple Pricing",
    "price.title": "Choose the Perfect Plan",
    "price.titleAccent": "for Your Workshop",
    "price.subtitle": "Start free, upgrade when you're ready. Secure billing via Stripe & PayPal. Cancel anytime.",
    "price.popular": "Most Popular",
    
    "price.hobby.name": "Hobbyist",
    "price.hobby.price": "$9",
    "price.hobby.period": "/month",
    "price.hobby.desc": "Perfect for makers starting out or hobbyists.",
    "price.hobby.f1": "Up to 10 active projects",
    "price.hobby.f2": "Laser Settings Presets",
    "price.hobby.f3": "Basic Cost Calculator",
    "price.hobby.f4": "10 free PDF invoices / mo",
    "price.hobby.f5": "($0.50 per add. invoice)",
    "price.hobby.f6": "❌ Design Library locked",
    "price.hobby.cta": "Get Hobbyist Access",
    
    "price.pro.name": "Pro Workshop",
    "price.pro.price": "$19",
    "price.pro.period": "/month",
    "price.pro.desc": "Everything you need to run a profitable workshop.",
    "price.pro.f1": "Unlimited active projects",
    "price.pro.f2": "Unlocked Design Library",
    "price.pro.f3": "Unlimited PDF Invoices",
    "price.pro.f4": "Nesting Estimator & Alerts",
    "price.pro.f5": "Client Relationship Manager",
    "price.pro.f6": "Up to 3 Machine Profiles",
    "price.pro.cta": "Get Pro Access",
    
    "price.biz.name": "Industrial",
    "price.biz.price": "$69",
    "price.biz.period": "/month",
    "price.biz.desc": "For professional teams and industrial makers.",
    "price.biz.f1": "Everything in Pro Workshop, plus:",
    "price.biz.f2": "Multi-user Team Access (5 users)",
    "price.biz.f3": "Unlimited Machine Profiles",
    "price.biz.f4": "Custom Branding on Invoices",
    "price.biz.f5": "API Access & Integrations",
    "price.biz.f6": "Priority 1-on-1 Support",
    "price.biz.cta": "Get Industrial Access",
    
    // Final CTA
    "final.title": "Stop Managing Your",
    "final.titleMid": "Workshop in",
    "final.titleAccent": "Spreadsheets.",
    "final.subtitle": "Join hundreds of laser and CNC makers who switched to 0Machine and finally know their real costs, track every job, and grow their business with confidence.",
    "final.cta.trial": "⚡ Start Your Free Trial",
    "final.cta.features": "Explore Features",
    "final.terms": "3 days free · $9/mo after · Cancel anytime · No credit card required",
    
    // Footer
    "foot.desc": "The all-in-one planner for laser cutters and CNC makers. Track everything. Grow your business.",
    "foot.hours": "Mon - Fri: 9am - 5pm MST",
    "foot.payments": "Secure payments via Stripe & PayPal",
    "foot.billed": "Billed monthly",
    "foot.cancel": "Cancel anytime",
    "foot.copyright": "© 2026 0Machine Planner. Built for makers. ⚡"
  },
  fr: {
    // Loader
    "loader.loading": "Chargement de l'expérience...",
    // Navbar
    "nav.features": "Fonctionnalités",
    "nav.benefits": "Avantages",
    "nav.workflow": "Fonctionnement",
    "nav.pricing": "Tarifs",
    "nav.signin": "Connexion",
    "nav.trial": "Essai Gratuit",
    
    // Hero
    "hero.badge": "Conçu pour les créateurs Laser & CNC",
    "hero.title1": "Gérez votre activité",
    "hero.title2": "laser ",
    "hero.titleAccent": "plus intelligemment.",
    "hero.subtitle": "Suivez les matériaux, calculez les coûts, gérez les clients et générez des devis — le tout depuis une magnifique application conçue pour les découpeurs laser et créateurs CNC.",
    "hero.ctaTrial": "⚡ Essai Gratuit",
    "hero.ctaFeatures": "Fonctionnalités →",
    "hero.trialNote": "3 jours gratuits · puis 9 $/mois · annulez à tout moment",
    
    // Benefits
    "benefits.badge": "Avantages Réels",
    "benefits.title": "Chaque fonctionnalité vous fait économiser",
    "benefits.titleAccent": "Temps et Argent",
    "benefits.subtitle": "Voici comment 0Machine vous aide à arrêter de perdre des heures en paperasse pour vous concentrer sur vos bénéfices.",
    
    "benefits.calc.feature": "Calculateur de Coûts",
    "benefits.calc.title": "Déterminez votre coût réel par travail — instantanément",
    "benefits.calc.desc": "Saisissez les matériaux, le temps laser, l'électricité, la main-d'œuvre et l'usure de la machine. Obtenez une ventilation des coûts en temps réel avec un prix de vente recommandé. Ne sous-estimez plus jamais un travail.",
    "benefits.calc.outcome": "Arrêtez de perdre de l'argent sur des travaux que vous pensiez rentables",
    "benefits.calc.stat": "3x",
    "benefits.calc.statLabel": "devis plus rapides",
    
    "benefits.inv.feature": "Inventaire des Matériaux",
    "benefits.inv.title": "Suivez chaque feuille, chaque découpe, chaque centime",
    "benefits.inv.desc": "Gérez votre stock de contreplaqué, acrylique, MDF et cuir avec la valeur de l'inventaire en temps réel. Recevez des alertes de stock bas avant de tomber en panne en plein projet.",
    "benefits.inv.outcome": "Éliminez les pénuries surprises de matériaux pendant la production",
    "benefits.inv.stat": "0",
    "benefits.inv.statLabel": "ruptures de stock",
    
    "benefits.order.feature": "Gestion des Commandes",
    "benefits.order.title": "Chaque commande est suivie de la demande à la livraison",
    "benefits.order.desc": "Visualisez toutes les commandes en un coup d'œil — En attente, En cours, Terminées. Suivez les noms des clients, les dates d'échéance, les revenus gagnés et les paiements en attente.",
    "benefits.order.outcome": "Ne manquez jamais une date limite et n'oubliez jamais une commande client",
    "benefits.order.stat": "100%",
    "benefits.order.statLabel": "visibilité des commandes",
    
    "benefits.presets.feature": "Préréglages Laser",
    "benefits.presets.title": "Des réglages parfaits à chaque fois, sans devinettes",
    "benefits.presets.desc": "Enregistrez la vitesse, la puissance, la fréquence, les passes et les paramètres d'assistance d'air par matériau. Chargez instantanément les préréglages lors du passage d'un matériau à un autre.",
    "benefits.presets.outcome": "Réduisez le gaspillage de matériaux dû à de mauvais réglages de la machine",
    "benefits.presets.stat": "10s",
    "benefits.presets.statLabel": "pour charger",
    
    "benefits.quote.feature": "Générateur de Devis",
    "benefits.quote.title": "Envoyez des devis professionnels en moins d'une minute",
    "benefits.quote.desc": "Créez des devis détaillés avec des articles individuels, la TVA et les totaux. Soyez professionnel et concluez vos ventes plus rapidement avec des documents prêts pour vos clients.",
    "benefits.quote.outcome": "Gagnez plus de clients avec des devis soignés et instantanés",
    "benefits.quote.stat": "60s",
    "benefits.quote.statLabel": "pour envoyer",
    
    "benefits.nest.feature": "Estimateur d'Imbrication",
    "benefits.nest.title": "Maximisez chaque feuille, minimisez le gaspillage",
    "benefits.nest.desc": "Calculez le nombre de pièces qui rentrent sur une feuille avant de couper. Optimisez l'utilisation des matériaux et réduisez les chutes sur chaque travail.",
    "benefits.nest.outcome": "Économisez jusqu'à 30 % sur les coûts de matériaux grâce à une imbrication intelligente",
    "benefits.nest.stat": "30%",
    "benefits.nest.statLabel": "de déchets en moins",

    // Feature Showcase
    "features.badge": "Fonctionnalités",
    "features.title": "Conçu pour votre façon de travailler",
    "features.subtitle": "Explorez les outils clés qui facilitent la gestion de votre atelier au quotidien.",
    
    "features.tab.dashboard": "Tableau de Bord",
    "features.tab.calc": "Calculateur",
    "features.tab.inventory": "Inventaire",
    "features.tab.orders": "Commandes",
    "features.tab.presets": "Préréglages",
    
    "features.db.title": "Tout votre atelier en un coup d'œil",
    "features.db.subtitle": "Consultez le nombre total de projets, les tâches actives, le travail terminé et les revenus générés d'un seul coup d'œil. Plus besoin de deviner.",
    "features.db.h1": "Statistiques en temps réel",
    "features.db.h2": "Suivi des revenus",
    "features.db.h3": "Flux de projets récents",
    "features.db.h4": "Vue globale des statuts",
    
    "features.calc.title": "Calcul des coûts et bénéfices en direct",
    "features.calc.subtitle": "Saisissez le coût des matériaux, les dimensions des plaques, le temps laser, l'électricité, l'usure de la machine et la main-d'œuvre. Visualisez instantanément la ventilation des coûts et le prix recommandé.",
    "features.calc.h1": "Coût matière par unité",
    "features.calc.h2": "Suivi machine et énergie",
    "features.calc.h3": "Calculateur de marge",
    "features.calc.h4": "Tarification recommandée",
    
    "features.inv.title": "Évaluation des stocks et alertes en direct",
    "features.inv.subtitle": "Suivez le bois, l'acrylique et vos matériaux personnalisés par feuille ou par taille de chute. Recevez des notifications automatiques dès qu'un niveau de stock est critique.",
    "features.inv.h1": "Registres bois et acrylique",
    "features.inv.h2": "Alertes de stock bas",
    "features.inv.h3": "Déduction automatique du stock",
    "features.inv.h4": "Suivi du coût unitaire",
    
    "features.orders.title": "Pipeline de production visuel",
    "features.orders.subtitle": "Suivez l'état de chaque commande, de la demande de devis à la livraison finale. Fixez des délais, enregistrez les paiements et ajoutez des photos.",
    "features.orders.h1": "Tableau de statuts interactif",
    "features.orders.h2": "Gestion des relations clients",
    "features.orders.h3": "Suivi des revenus et des soldes",
    "features.orders.h4": "Calendrier des dates limites",
    
    "features.presets.title": "Votre bibliothèque de réglages d'atelier",
    "features.presets.subtitle": "Ne gaspillez plus de temps et de matière en tests de découpe. Enregistrez la vitesse, la puissance, la fréquence et le flux d'air pour chaque type de laser.",
    "features.presets.h1": "Support multi-machines",
    "features.presets.h2": "Onglets d'épaisseur matière",
    "features.presets.h3": "Modes Vecteur vs Gravure",
    "features.presets.h4": "Recherche de réglages rapide",
    
    "features.tab.nesting": "Nesting / Imbrication",
    "features.tab.quotes": "Devis & Factures",
    "features.tab.clients": "Clients CRM",
    "features.tab.analytics": "Analyses",
    
    "features.nest.title": "Optimisez l'imbrication et réduisez les chutes",
    "features.nest.subtitle": "Calculez comment disposer vos pièces sur une plaque de bois ou d'acrylique avant la découpe. Économisez jusqu'à 30% sur vos plaques.",
    "features.nest.h1": "Imbrication visuelle",
    "features.nest.h2": "Calculateur de chutes",
    "features.nest.h3": "Rendement optimisé",
    "features.nest.h4": "Économies estimées",

    "features.quotes.title": "Envoyez des devis et factures PDF professionnels",
    "features.quotes.subtitle": "Convertissez les estimations de projet en documents client détaillés en quelques secondes. Exportez des PDF avec vos coordonnées bancaires, taxes et liens de paiement.",
    "features.quotes.h1": "Export de factures PDF",
    "features.quotes.h2": "Calcul automatique des taxes",
    "features.quotes.h3": "Suivi des statuts de facturation",
    "features.quotes.h4": "Personnalisation de la marque",

    "features.clients.title": "Gerez vos clients fideles et leurs soldes",
    "features.clients.subtitle": "Suivez les coordonnées, l'historique des commandes et les paiements en attente de chaque client. Consultez leur valeur à vie (LTV) pour identifier vos meilleurs acheteurs.",
    "features.clients.h1": "Registre client",
    "features.clients.h2": "Valeur à vie (LTV)",
    "features.clients.h3": "Suivi des soldes dus",
    "features.clients.h4": "Facturation instantanée",

    "features.analytics.title": "Comprenez votre activité grâce à des chiffres clés",
    "features.analytics.subtitle": "Suivez le chiffre d'affaires, le taux d'achèvement des tâches, les projets phares, l'utilisation des stocks et le coût moyen par tâche.",
    "features.analytics.h1": "Suivi du chiffre d'affaires",
    "features.analytics.h2": "Taux de réussite des tâches",
    "features.analytics.h3": "Statistiques projets phares",
    "features.analytics.h4": "Analyse temps & coûts",

    // Interactive Mockup Texts
    "mock.total": "Total",
    "mock.inprogress": "En Cours",
    "mock.completed": "Terminé",
    "mock.revenue": "Revenu",
    "mock.recent": "PROJETS RÉCENTS",
    "mock.coasters": "Sous-verres Perso",
    "mock.birch": "Bouleau Contreplaqué 3mm",
    "mock.sheet": "Coût Plaque",
    "mock.usage": "Utilisation",
    "mock.laser": "Temps Laser",
    "mock.labor": "Main-d'œuvre",
    "mock.cost": "Coût Total",
    "mock.price": "Prix Rec.",
    "mock.wood": "Bois - Bouleau 3mm",
    "mock.acrylic": "Acrylique - Rouge 3mm",
    "mock.sheets": "plaques",
    "mock.stock": "En Stock",
    "mock.pending": "En attente",
    "mock.deliv": "Livré",
    "mock.bal": "Reste Dû",
    "mock.speed": "Vitesse",
    "mock.power": "Puissance",
    
    // Comparison
    "comp.badge": "Comparatif",
    "comp.title": "Feuilles de calcul vs",
    "comp.titleAccent": "0Machine",
    "comp.subtitle": "Pourquoi les créateurs abandonnent Excel pour un planificateur dédié.",
    "comp.col.old": "Méthode Traditionnelle",
    "comp.col.new": "La Méthode 0Machine",
    "comp.old.1": "Tarification calculée au pifomètre — perte d'argent un projet sur deux",
    "comp.old.2": "Fichiers de conception éparpillés sur clés USB, dossiers de bureau et applications de messagerie",
    "comp.old.3": "Revenus suivis sur des tableurs désordonnés — aucune idée de la rentabilité réelle",
    "comp.old.4": "Paramètres laser écrits sur des post-it — mauvaise puissance, matière gaspillée",
    "comp.old.5": "Commandes gérées de tête — dates limites manquées et clients oubliés",
    "comp.old.6": "Pénuries de matériaux découvertes en plein travail — production arrêtée, clients en attente",
    "comp.new.1": "Le calculateur indique instantanément le coût de revient réel et le prix de vente conseillé",
    "comp.new.2": "Chaque projet est organisé avec photos, coûts, temps, matériaux et infos clients",
    "comp.new.3": "Des analyses intelligentes indiquent les revenus, les meilleurs projets et les tendances",
    "comp.new.4": "Préréglages laser chargés en 10 secondes — des réglages parfaits à chaque fois",
    "comp.new.5": "Suivi des commandes en cours avec dates limites et coordonnées clients",
    "comp.new.6": "L'inventaire affiche en direct les niveaux de stock et la valeur totale — plus de panne",
    
    // Workflow
    "flow.badge": "Fonctionnement",
    "flow.title": "De la configuration à la livraison en",
    "flow.titleAccent": "4 étapes",
    "flow.step1.title": "Créer & Organiser",
    "flow.step1.desc": "Ajoutez votre projet avec matériaux, photos et détails clients. Utilisez des modèles pour lancer des tâches récurrentes en un clic.",
    "flow.step2.title": "Calculer & Chiffrer",
    "flow.step2.desc": "Utilisez le calculateur de coûts pour obtenir votre coût de revient réel : matière, temps machine, main-d'œuvre, énergie. Générez un devis pro.",
    "flow.step3.title": "Produire & Suivre",
    "flow.step3.desc": "Chargez vos préréglages laser, lancez le minuteur intégré et suivez la progression. Les commandes passent d'en attente à en cours automatiquement.",
    "flow.step4.title": "Livrer & Développer",
    "flow.step4.desc": "Exportez des rapports PDF, analysez vos statistiques et découvrez les projets les plus rentables. Développez-vous grâce aux données.",

    // Product Showcase
    "showcase.badge": "Interface Produit",
    "showcase.title": "Conçu pour votre navigateur et mobile",
    "showcase.subtitle": "Accédez à votre tableau de bord depuis votre tablette d'atelier ou votre smartphone.",
    "showcase.label.db": "Tableau de Bord",
    "showcase.desc.db": "Suivez chaque projet avec son coût et temps",
    "showcase.label.detail": "Détails du Projet",
    "showcase.desc.detail": "Détail complet des coûts avec export PDF",
    "showcase.label.stats": "Analyses Intelligentes",
    "showcase.desc.stats": "Revenus, taux d'achèvement et tendances",
    
    // Social Proof
    "social.badge": "Témoignages",
    "social.title": "Recommandé par les créateurs",
    "social.subtitle": "Ce que les propriétaires d'ateliers disent de 0Machine Planner.",
    "social.role.laser": "Propriétaire d'Atelier Laser",
    "social.role.cnc": "Artisan CNC",
    "social.role.engrave": "Graveur Personnalisé",
    "social.stat.projects": "Projets Suivis",
    "social.stat.satisfaction": "Satisfaction Client",
    "social.stat.hours": "Heures Économisées / Mois",
    "social.stat.rating": "Note App Store",
    "social.t1.name": "Jason R.",
    "social.t1.role": "Graveur Laser Professionnel",
    "social.t1.text": "Je suivais tout sur l'appli Notes. Maintenant, j'ai des ventilations de coûts complètes pour chaque projet et je sais exactement quoi facturer. L'export PDF vaut le coup à lui seul.",
    "social.t2.name": "Maria C.",
    "social.t2.role": "Créatrice d'Enseignes",
    "social.t2.text": "La gestion des clients est géniale. J'ai 12 clients réguliers et je vois en un clin d'œil les revenus générés par chacun. Ça a changé mon activité secondaire.",
    "social.t3.name": "Tyler P.",
    "social.t3.role": "Artisan d'Atelier CNC",
    "social.t3.text": "Les profils de machines ont tout changé. J'ai 3 machines avec des réglages différents — maintenant je charge le profil et je suis prêt. Fini les erreurs de réglage.",
    "social.t4.name": "Emma K.",
    "social.t4.role": "Vendeuse de Foires",
    "social.t4.text": "Interface super propre et très rapide. J'adore le fait que l'appli fonctionne aussi hors ligne. Je l'utilise sur les foires pour montrer le coût estimé aux clients.",
    "social.t5.name": "David M.",
    "social.t5.role": "Créateur Etsy Laser",
    "social.t5.text": "Les modèles sont un gain de temps massif. J'ai modèles pour mes articles de découpe laser les plus populaires et je lance un projet en 10 secondes chrono. J'adore.",
    "social.t6.name": "Rachel S.",
    "social.t6.role": "Productrice Petite Série",
    "social.t6.text": "L'essai gratuit de 3 jours m'a convaincue. J'ai configuré 5 projets dès la première heure. Au deuxième jour, je savais déjà que j'allais m'abonner. Vaut chaque dollar.",
    
    // Pricing
    "price.badge": "Tarifs Simples",
    "price.title": "Choisissez le Plan Parfait",
    "price.titleAccent": "pour Votre Atelier",
    "price.subtitle": "Commencez gratuitement, passez à l'offre supérieure quand vous le souhaitez. Facturation sécurisée via Stripe et PayPal.",
    "price.popular": "Le Plus Populaire",
    
    "price.hobby.name": "Amateur",
    "price.hobby.price": "9 $",
    "price.hobby.period": "/mois",
    "price.hobby.desc": "Idéal pour les créateurs débutants et les amateurs.",
    "price.hobby.f1": "Jusqu'à 10 projets actifs",
    "price.hobby.f2": "Préréglages de vitesse & puissance",
    "price.hobby.f3": "Calculateur de coût de base",
    "price.hobby.f4": "10 factures PDF gratuites / mois",
    "price.hobby.f5": "(0,50 $ par facture sup.)",
    "price.hobby.f6": "❌ Bibliothèque de design verrouillée",
    "price.hobby.cta": "Accès Amateur",
    
    "price.pro.name": "Atelier Pro",
    "price.pro.price": "19 $",
    "price.pro.period": "/mois",
    "price.pro.desc": "Tout ce dont vous avez besoin pour gérer un atelier rentable.",
    "price.pro.f1": "Projets actifs illimités",
    "price.pro.f2": "Bibliothèque de design déverrouillée",
    "price.pro.f3": "Factures PDF illimitées",
    "price.pro.f4": "Estimateur d'imbrication & alertes",
    "price.pro.f5": "Gestionnaire de clients (CRM)",
    "price.pro.f6": "Jusqu'à 3 profils de machines",
    "price.pro.cta": "Accès Pro",
    
    "price.biz.name": "Industriel",
    "price.biz.price": "69 $",
    "price.biz.period": "/mois",
    "price.biz.desc": "Pour les équipes professionnelles et créateurs industriels.",
    "price.biz.f1": "Tout ce qui est dans l'Atelier Pro, plus :",
    "price.biz.f2": "Accès équipe multi-utilisateurs (5)",
    "price.biz.f3": "Profils de machines illimités",
    "price.biz.f4": "Marque personnalisée sur factures",
    "price.biz.f5": "Accès API & Intégrations",
    "price.biz.f6": "Support prioritaire 1-sur-1",
    "price.biz.cta": "Accès Industriel",
    
    // Final CTA
    "final.title": "Arrêtez de gérer votre",
    "final.titleMid": "atelier sur des",
    "final.titleAccent": "tableurs.",
    "final.subtitle": "Rejoignez des centaines d'artisans laser et CNC qui ont choisi 0Machine pour connaître leurs coûts réels, suivre chaque commande et développer leur activité sereinement.",
    "final.cta.trial": "⚡ Commencer l'Essai Gratuit",
    "final.cta.features": "Explorer les Fonctionnalités",
    "final.terms": "3 jours gratuits · 9 $/mois ensuite · Annulez à tout moment · Pas de carte requise",
    
    // Footer
    "foot.desc": "Le planificateur tout-en-un pour les ateliers de découpe laser et CNC. Suivez tout. Développez votre entreprise.",
    "foot.hours": "Lun - Ven : 9h00 - 17h00 MST",
    "foot.payments": "Paiements sécurisés via Stripe & PayPal",
    "foot.billed": "Facturé mensuellement",
    "foot.cancel": "Annulation à tout moment",
    "foot.copyright": "© 2026 0Machine Planner. Conçu pour les créateurs. ⚡"
  },
  es: {
    // Loader
    "loader.loading": "Cargando experiencia...",
    // Navbar
    "nav.features": "Características",
    "nav.benefits": "Beneficios",
    "nav.workflow": "Cómo Funciona",
    "nav.pricing": "Precios",
    "nav.signin": "Conexión",
    "nav.trial": "Prueba Gratuita",
    
    // Hero
    "hero.badge": "Creado para creadores de Láser y CNC",
    "hero.title1": "Gestione su negocio",
    "hero.title2": "de láser ",
    "hero.titleAccent": "más inteligentemente.",
    "hero.subtitle": "Realice un seguimiento de materiales, calcule costos, gestione clientes y genere presupuestos, todo desde una hermosa aplicación diseñada para cortadoras láser y creadores de CNC.",
    "hero.ctaTrial": "⚡ Prueba Gratuita",
    "hero.ctaFeatures": "Características →",
    "hero.trialNote": "3 días gratis · luego $9/mes · cancele cuando quiera",
    
    // Benefits
    "benefits.badge": "Beneficios Reales",
    "benefits.title": "Cada función le ahorra",
    "benefits.titleAccent": "Tiempo y Dinero",
    "benefits.subtitle": "Así es como 0Machine le ayuda a dejar de perder horas en administración para enfocarse en sus ganancias.",
    
    "benefits.calc.feature": "Calculadora de Costos",
    "benefits.calc.title": "Conozca su costo real por trabajo — al instante",
    "benefits.calc.desc": "Introduzca materiales, tiempo de láser, electricidad, mano de obra y desgaste de la máquina. Obtenga un desglose de costos en tiempo real con el precio de venta recomendado. Nunca vuelva a cobrar de menos por un trabajo.",
    "benefits.calc.outcome": "Deje de perder dinero en trabajos que creía que eran rentables",
    "benefits.calc.stat": "3x",
    "benefits.calc.statLabel": "devisas más rápidas",
    
    "benefits.inv.feature": "Inventario de Materiales",
    "benefits.inv.title": "Siga cada hoja, cada corte, cada centavo",
    "benefits.inv.desc": "Gestione su inventario de madera contrachapada, acrílico, MDF y cuero con el valor del inventario en tiempo real. Reciba alertas de stock bajo antes de quedarse sin material a mitad del proyecto.",
    "benefits.inv.outcome": "Elimine la escasez sorpresa de materiales durante la producción",
    "benefits.inv.stat": "0",
    "benefits.inv.statLabel": "faltas de stock",
    
    "benefits.order.feature": "Gestión de Pedidos",
    "benefits.order.title": "Cada pedido rastreado desde la solicitud hasta la entrega",
    "benefits.order.desc": "Vea todos los pedidos de un vistazo: Pendientes, En curso, Completados. Rastree nombres de clientes, fechas de vencimiento, ingresos obtenidos y pagos pendientes.",
    "benefits.order.outcome": "Nunca pierda una fecha límite ni olvide el pedido de un cliente",
    "benefits.order.stat": "100%",
    "benefits.order.statLabel": "visibilidad de pedidos",
    
    "benefits.presets.feature": "Ajustes de Láser",
    "benefits.presets.title": "Ajustes perfectos cada vez, sin adivinanzas",
    "benefits.presets.desc": "Guarde la velocidad, potencia, frecuencia, pasadas y ajustes de asistencia de aire por material. Cargue los ajustes preestablecidos al instante al cambiar de material.",
    "benefits.presets.outcome": "Reduzca el desperdicio de material debido a una configuración incorrecta de la máquina",
    "benefits.presets.stat": "10s",
    "benefits.presets.statLabel": "para cargar",
    
    "benefits.quote.feature": "Generador de Presupuestos",
    "benefits.quote.title": "Envíe presupuestos profesionales en menos de un minuto",
    "benefits.quote.desc": "Cree presupuestos detallados con artículos, IVA y totales. Luzca profesional y cierre tratos más rápido con documentos listos para el cliente.",
    "benefits.quote.outcome": "Gane más clientes con presupuestos profesionales e instantáneos",
    "benefits.quote.stat": "60s",
    "benefits.quote.statLabel": "para enviar",
    
    "benefits.nest.feature": "Estimador de Nesting",
    "benefits.nest.title": "Maximice cada hoja, minimice el desperdicio",
    "benefits.nest.desc": "Calcule cuántas piezas caben en una hoja antes de cortar. Optimice el uso del material y reduzca los retales en cada trabajo.",
    "benefits.nest.outcome": "Ahorre hasta un 30% en costos de material con un nesting más inteligente",
    "benefits.nest.stat": "30%",
    "benefits.nest.statLabel": "menos residuo",

    // Feature Showcase
    "features.badge": "Características",
    "features.title": "Diseñado para su forma de trabajar",
    "features.subtitle": "Explore las herramientas clave que facilitan la gestión de su taller al día.",
    
    "features.tab.dashboard": "Panel de Control",
    "features.tab.calc": "Calculadora",
    "features.tab.inventory": "Inventario",
    "features.tab.orders": "Pedidos",
    "features.tab.presets": "Ajustes",
    
    "features.db.title": "Todo su taller en un solo vistazo",
    "features.db.subtitle": "Consulte proyectos totales, trabajos activos, trabajo completado e ingresos de un vistazo. No más adivinanzas.",
    "features.db.h1": "Estadísticas en tiempo real",
    "features.db.h2": "Seguimiento de ingresos",
    "features.db.h3": "Proyectos recientes",
    "features.db.h4": "Resumen de estados",
    
    "features.calc.title": "Cálculo de costos y ganancias en vivo",
    "features.calc.subtitle": "Introduzca costos, dimensiones, tiempo de láser, energía y mano de obra. Vea instantáneamente el desglose detallado de costos y el precio recomendado.",
    "features.calc.h1": "Costo por unidad de material",
    "features.calc.h2": "Seguimiento de máquina y energía",
    "features.calc.h3": "Calculadora de margen",
    "features.calc.h4": "Precios recomendados",
    
    "features.inv.title": "Valoración de inventario y alertas en vivo",
    "features.inv.subtitle": "Rastree madera, acrílico y materiales personalizados por hoja o sobrante. Reciba notificaciones automáticas cuando el stock esté bajo.",
    "features.inv.h1": "Registro de madera y acrílico",
    "features.inv.h2": "Alertas de stock bajo",
    "features.inv.h3": "Deducción automática de stock",
    "features.inv.h4": "Costo por material",
    
    "features.orders.title": "Pipeline de producción visual",
    "features.orders.subtitle": "Siga el estado desde la solicitud de presupuesto hasta la entrega final. Defina fechas, registre pagos y añada fotos de proyectos.",
    "features.orders.h1": "Tablero de estados interactivo",
    "features.orders.h2": "Seguimiento de clientes",
    "features.orders.h3": "Registro de ingresos y saldos",
    "features.orders.h4": "Calendarios de entrega",
    
    "features.presets.title": "Biblioteca de ajustes de taller",
    "features.presets.subtitle": "No vuelva a desperdiciar material en pruebas. Guarde velocidad, potencia, frecuencia y flujo de aire para cada láser.",
    "features.presets.h1": "Soporte multi-máquina",
    "features.presets.h2": "Pestañas de espesores",
    "features.presets.h3": "Modos Vector vs Grabado",
    "features.presets.h4": "Búsqueda rápida de ajustes",
    
    "features.tab.nesting": "Estimador de Nesting",
    "features.tab.quotes": "Presupuestos y Facturas",
    "features.tab.clients": "Gestor de Clientes",
    "features.tab.analytics": "Análisis",
    
    "features.nest.title": "Optimice las planchas y minimice los recortes",
    "features.nest.subtitle": "Calcule cuántas piezas caben en una plancha de madera o acrílico antes de cortar. Ahorre hasta un 30% en costos de material optimizando la distribución.",
    "features.nest.h1": "Nesting de planchas visual",
    "features.nest.h2": "Estimador de retales",
    "features.nest.h3": "Rendimiento optimizado",
    "features.nest.h4": "Cálculo de ahorro de costes",

    "features.quotes.title": "Envíe presupuestos y facturas en PDF profesionales",
    "features.quotes.subtitle": "Convierta presupuestos en facturas finales detalladas en segundos. Exporte PDF con sus datos bancarios, impuestos locales y enlaces directos de pago.",
    "features.quotes.h1": "Exportación de facturas PDF",
    "features.quotes.h2": "Cálculo automático de IVA",
    "features.quotes.h3": "Seguimiento de estados de cobro",
    "features.quotes.h4": "Identidad de marca personalizada",

    "features.clients.title": "Gestione clientes recurrentes y saldos",
    "features.clients.subtitle": "Rastree datos de contacto, pedidos y saldos pendientes de cada comprador. Consulte su valor de por vida (LTV) para identificar a sus clientes estrella.",
    "features.clients.h1": "Historial de clientes",
    "features.clients.h2": "Valor de por vida (LTV)",
    "features.clients.h3": "Rastreador de saldos",
    "features.clients.h4": "Facturación rápida",

    "features.analytics.title": "Entienda su negocio con números inteligentes",
    "features.analytics.subtitle": "Rastree ingresos totales, tasas de finalización, proyectos estrella, uso de inventario y coste medio por trabajo.",
    "features.analytics.h1": "Seguimiento de ingresos",
    "features.analytics.h2": "Tasas de éxito del proyecto",
    "features.analytics.h3": "Estadísticas de proyectos estrella",
    "features.analytics.h4": "Análisis de tiempo y costo",

    // Interactive Mockup Texts
    "mock.total": "Total",
    "mock.inprogress": "En Proceso",
    "mock.completed": "Completado",
    "mock.revenue": "Ingresos",
    "mock.recent": "PROYECTOS RECIENTES",
    "mock.coasters": "Posavasos Perso",
    "mock.birch": "Abedul Contrachapado 3mm",
    "mock.sheet": "Costo de Hoja",
    "mock.usage": "Uso",
    "mock.laser": "Tiempo Láser",
    "mock.labor": "Mano de Obra",
    "mock.cost": "Costo Total",
    "mock.price": "Precio Rec.",
    "mock.wood": "Madera - Abedul 3mm",
    "mock.acrylic": "Acrílico - Rojo 3mm",
    "mock.sheets": "hojas",
    "mock.stock": "En Stock",
    "mock.pending": "Pendiente",
    "mock.deliv": "Entregado",
    "mock.bal": "Saldo Pend.",
    "mock.speed": "Velocidad",
    "mock.power": "Potencia",
    
    // Comparison
    "comp.badge": "Comparativa",
    "comp.title": "Hojas de cálculo vs",
    "comp.titleAccent": "0Machine",
    "comp.subtitle": "Por qué los creadores están dejando Excel por un planificador dedicado.",
    "comp.col.old": "Método Tradicional",
    "comp.col.new": "El Método 0Machine",
    "comp.old.1": "Precios calculados por intuición: perdiendo dinero en uno de cada dos trabajos",
    "comp.old.2": "Archivos de diseño dispersos en USB, carpetas de escritorio y chats",
    "comp.old.3": "Ingresos rastreados en hojas de cálculo desordenadas: sin saber qué es rentable",
    "comp.old.4": "Ajustes de láser anotados en post-its: potencia incorrecta y material desperdiciado",
    "comp.old.5": "Pedidos gestionados de memoria: plazos vencidos y clientes olvidados",
    "comp.old.6": "Faltas de material a mitad del trabajo: producción detenida y clientes esperando",
    "comp.new.1": "La calculadora muestra el costo real de producción y el precio sugerido al instante",
    "comp.new.2": "Cada proyecto organizado con fotos, costos, tiempo, materiales e información de clientes",
    "comp.new.3": "Los análisis muestran ingresos, proyectos estrella, tasas de éxito y tendencias",
    "comp.new.4": "Ajustes preestablecidos cargados en 10 segundos: configuración perfecta cada vez",
    "comp.new.5": "Pedidos rastreados con fechas de entrega y nombres de clientes",
    "comp.new.6": "El inventario muestra niveles de stock y el valor total en tiempo real para no quedarse sin nada",
    
    // Workflow
    "flow.badge": "Cómo Funciona",
    "flow.title": "De la configuración a la entrega en",
    "flow.titleAccent": "4 pasos",
    "flow.step1.title": "Crear y Organizar",
    "flow.step1.desc": "Añada su proyecto con materiales, fotos y detalles de clientes. Use plantillas para iniciar tareas recurrentes en segundos.",
    "flow.step2.title": "Calcular y Cotizar",
    "flow.step2.desc": "Use la calculadora para obtener su costo real: material, tiempo de máquina, mano de obra, energía. Genere presupuestos pro.",
    "flow.step3.title": "Producir y Seguir",
    "flow.step3.desc": "Cargue sus ajustes de láser, inicie el temporizador y siga el progreso. Los pedidos cambian a en curso automáticamente.",
    "flow.step4.title": "Entregar y Crecer",
    "flow.step4.desc": "Exporte reportes PDF, analice sus estadísticas y descubra qué proyectos generan más ingresos. Crezca con datos, no con dudas.",

    // Product Showcase
    "showcase.badge": "Interfaz de Producto",
    "showcase.title": "Creado para su navegador y móvil",
    "showcase.subtitle": "Acceda a su panel de control desde la tableta de su taller o su teléfono móvil.",
    "showcase.label.db": "Panel del Proyecto",
    "showcase.desc.db": "Rastree cada proyecto con tiempo y costos",
    "showcase.label.detail": "Detalles del Proyecto",
    "showcase.desc.detail": "Desglose de costos con exportación PDF",
    "showcase.label.stats": "Análisis Inteligente",
    "showcase.desc.stats": "Ingresos, tasas de éxito y tendencias",
    
    // Social Proof
    "social.badge": "Testimonios",
    "social.title": "Recomendado por los creadores",
    "social.subtitle": "Lo que dicen los dueños de talleres sobre 0Machine Planner.",
    "social.role.laser": "Dueño de Taller Láser",
    "social.role.cnc": "Artesano CNC",
    "social.role.engrave": "Grabador Personalizado",
    "social.stat.projects": "Proyectos Rastreados",
    "social.stat.satisfaction": "Satisfacción del Cliente",
    "social.stat.hours": "Horas Ahorradas al Mes",
    "social.stat.rating": "Calificación App Store",
    "social.t1.name": "Jason R.",
    "social.t1.role": "Dueño de Tienda Láser",
    "social.t1.text": "Antes rastreaba todo en la app de Notas. Ahora tengo desgloses de costos completos para cada proyecto y sé exactamente qué cobrar. Solo la exportación PDF ya lo vale.",
    "social.t2.name": "Maria C.",
    "social.t2.role": "Fabricante de Letreros",
    "social.t2.text": "La gestión de clientes es brillante. Tengo 12 clientes habituales y puedo ver de un vistazo cuántos ingresos aporta cada uno. Un cambio total para mi negocio secundario.",
    "social.t3.name": "Tyler P.",
    "social.t3.role": "Propietario de Taller CNC",
    "social.t3.text": "Los perfiles de máquina lo cambiaron todo. Tengo 3 máquinas con configuraciones totalmente diferentes: cargo el perfil y listo. Nunca más me equivoco con los ajustes.",
    "social.t4.name": "Emma K.",
    "social.t4.role": "Vendedora de Ferias",
    "social.t4.text": "Interfaz super limpia y rápida. Me encanta que funcione sin conexión. La uso en ferias de artesanía para mostrar a los clientes el costo exacto antes de empezar.",
    "social.t5.name": "David M.",
    "social.t5.role": "Creador Etsy Láser",
    "social.t5.text": "La función de plantillas ahorra muchísimo tiempo. Tengo plantillas para mis artículos cortados con láser más populares y empiezo un trabajo en 10 segundos. Me encanta.",
    "social.t6.name": "Rachel S.",
    "social.t6.role": "Productora en Lotes Pequeños",
    "social.t6.text": "La prueba de 3 días cerró el trato. Configuré 5 proyectos en la primera hora. Al segundo día ya sabía que no iba a cancelar. Vale cada dólar.",
    
    // Pricing
    "price.badge": "Precios Simples",
    "price.title": "Elija el Plan Perfecto",
    "price.titleAccent": "para Su Taller",
    "price.subtitle": "Empiece gratis, actualice cuando esté listo. Pagos seguros mediante Stripe y PayPal.",
    "price.popular": "Más Popular",
    
    "price.hobby.name": "Aficionado",
    "price.hobby.price": "$9",
    "price.hobby.period": "/mes",
    "price.hobby.desc": "Perfecto para creadores principiantes o aficionados.",
    "price.hobby.f1": "Hasta 10 proyectos activos",
    "price.hobby.f2": "Ajustes preestablecidos de láser",
    "price.hobby.f3": "Calculadora de costo básica",
    "price.hobby.f4": "10 facturas PDF gratis / mes",
    "price.hobby.f5": "($0.50 por factura adicional)",
    "price.hobby.f6": "❌ Biblioteca de diseños bloqueada",
    "price.hobby.cta": "Acceso Aficionado",
    
    "price.pro.name": "Taller Pro",
    "price.pro.price": "$19",
    "price.pro.period": "/mes",
    "price.pro.desc": "Todo lo que necesita para dirigir un taller de láser rentable.",
    "price.pro.f1": "Proyectos activos ilimitados",
    "price.pro.f2": "Biblioteca de diseños desbloqueada",
    "price.pro.f3": "Facturas PDF ilimitadas",
    "price.pro.f4": "Estimador de nesting y alertas",
    "price.pro.f5": "Gestión de clientes (CRM)",
    "price.pro.f6": "Hasta 3 perfiles de máquinas",
    "price.pro.cta": "Acceso Pro",
    
    "price.biz.name": "Industrial",
    "price.biz.price": "$69",
    "price.biz.period": "/mes",
    "price.biz.desc": "Para equipos profesionales y creadores industriales.",
    "price.biz.f1": "Todo lo de Taller Pro, más:",
    "price.biz.f2": "Acceso de equipo multiusuario (5)",
    "price.biz.f3": "Perfiles de máquinas ilimitados",
    "price.biz.f4": "Marca personalizada en facturas",
    "price.biz.f5": "Acceso a API e integraciones",
    "price.biz.f6": "Soporte prioritario 1 a 1",
    "price.biz.cta": "Acceso Industrial",
    
    // Final CTA
    "final.title": "Deje de gestionar su",
    "final.titleMid": "taller en hojas",
    "final.titleAccent": "de cálculo.",
    "final.subtitle": "Únase a cientos de creadores de láser y CNC que eligieron 0Machine para conocer sus costos reales, seguir cada pedido y hacer crecer su negocio con confianza.",
    "final.cta.trial": "⚡ Iniciar Prueba Gratuita",
    "final.cta.features": "Explorar Características",
    "final.terms": "3 días gratis · $9/mes después · Cancele cuando quiera · Sin tarjeta requerida",
    
    // Footer
    "foot.desc": "El planificador todo en uno para talleres de corte láser y CNC. Rastree todo. Haga crecer su negocio.",
    "foot.hours": "Lun - Vie: 9:00 - 17:00 MST",
    "foot.payments": "Pagos seguros a través de Stripe y PayPal",
    "foot.billed": "Facturado mensualmente",
    "foot.cancel": "Cancele cuando quiera",
    "foot.copyright": "© 2026 0Machine Planner. Creado para makers. ⚡"
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState("en");

  // Load preferred language from localStorage after hydration, or auto-detect from browser
  useEffect(() => {
    const saved = localStorage.getItem("preferred_language");
    if (saved && ["en", "fr", "es"].includes(saved)) {
      setLanguageState(saved);
    } else {
      // Auto-detect browser language
      const browserLang = navigator.language || (navigator.languages && navigator.languages[0]);
      if (browserLang) {
        const langCode = browserLang.substring(0, 2).toLowerCase();
        if (["en", "fr", "es"].includes(langCode)) {
          setLanguageState(langCode);
        }
      }
    }
  }, []);

  const setLanguage = (lang) => {
    if (["en", "fr", "es"].includes(lang)) {
      setLanguageState(lang);
      localStorage.setItem("preferred_language", lang);
    }
  };

  const t = (key) => {
    return translations[language]?.[key] || translations["en"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
